### ISSUE TITLE
libman not found

### ISSUE THREAD

**Issue by enricoreich** [AdrianWilczynski/VSCodeLibMan#1]
Hello,

I struggled a bit to get your extension to work and find out that you need [Microsoft.Web.LibraryManager.Cli](https://docs.microsoft.com/en-us/aspnet/core/client-side/libman/libman-cli?view=aspnetcore-3.1) as a prerequisite installed globally as a dotnet tool (see link above).

Maybe it is a good idea to mention this in your README.md.

Thanks for this very useful extension. Keep it up! :)

**Comment by AdrianWilczynski** [comment]
Hey. Thanks for the report. I didn't even think about this. I'm gonna add requirements section to the readme.
